# algos/DepySM_ablation.py
# coding: utf-8
"""
Ablation study runner script (n_instance = 5, seed = 42)
=========================================================
Based on the updated ablation_study_design.md, this script implements the four
variants V2-V5 that require new computations.
Results for V0 (Full ProDSM) and V1 (w/o ADVR) already exist and are not
regenerated by this script:
    V0 -> res/<target>/inst5/updated_sim_matrix_iter5_p2_k13_d4_c15.json
    V1 -> res/<target>/inst5/sim_matrix.json

Variant mapping (numbering follows the latest ablation_study_design.md)
------------------------------------------------------------------------
  V2  w/o IND-Graph (Emb only) :
      Remove all IND edges (source-side inds.txt + target-side ind_edges.txt)
      when building the AID-Graph; keep only Bridge Edges and FD edges, then
      run PANE embedding without ADVR.
      Output goes to inst5_noind/.
      Self-consistency check: MusicRecordings has no IND, so V2 output should
      be element-wise equal to V1 sim_matrix.json.

  V3  Random Bridge Edges :
      Replace bridge edges with random sampling (build_bridge(random_bridge=True));
      the rest of the AID-Graph (including IND edges) and ADVR remain unchanged.
      Output goes to inst5_randbr/ (the old script used inst5_v/; now unified
      with semantic suffixes).

  V4  FD-only validation :
      Reuse inst5/sim_matrix.json; only re-run ADVR with dep_mode="fd"
      (validate FD only).
      Output: inst5/updated_sim_matrix_fd_only.json.

  V5  IND-only validation :
      Reuse inst5/sim_matrix.json; only re-run ADVR with dep_mode="ind"
      (validate IND only).
      Output: inst5/updated_sim_matrix_ind_only.json.
      Self-consistency check: MusicRecordings has no IND, so V5 output should
      be element-wise equal to V1 sim_matrix.json.

Fairness guarantees
-------------------
1. seed = 42 throughout (fixed upon module import; also fixed inside build_bridge).
2. V4/V5 share the embeddings from V0/V1 (inst5/sim_matrix.json); the only
   difference is the ADVR dependency set.
3. V2/V3 change the graph structure, so embeddings must be re-computed; each
   uses an independent inst_suffix to isolate outputs.
4. All variant target-instance sampling reuses the rng(42)+sorted logic from
   DepySM_batch_more.
5. ADVR hyperparameters are identical to V0 (see REFINE_PARAMS).

Usage (run from the algos/ directory)
--------------------------------------
    cd algos
    python DepySM_ablation.py
"""

import csv
import json
import os
import random
import subprocess

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

from dependency_refinement import refinement_iterative
from edge_builder import build_target_edge
from bridge_builder import build_bridge

# ── Global fixed random seed ──────────────────────────────────────
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ── Global constants ──────────────────────────────────────────────
N_INST        = 5          # Ablation study fixed n_instance = 5
TARGET_PYTHON = "/home/ouyang/anaconda3/envs/PANE/bin/python"
DATA_DIR_BASE = "../data"  # Run from algos/
ITER_NUM      = 5          # emb_sm.py --t
KAPPA         = 1024       # emb_sm.py --kappa

# ADVR hyperparameters: identical to the full method (V0)
REFINE_PARAMS = dict(max_iter=5, patience=2, k_min=1, k_max=3, decay=0.4, ceiling=1.5)

# ── Output filename constants ──────────────────────────────────────
UPDATED_FNAME_FULL  = "updated_sim_matrix_iter5_p2_k13_d4_c15.json"  # V0/V3 ADVR output
V4_FNAME            = "updated_sim_matrix_fd_only.json"               # V4
V5_FNAME            = "updated_sim_matrix_ind_only.json"              # V5

# ── inst_suffix constants ─────────────────────────────────────────
INST_BASE   = f"inst{N_INST}"          # Shared by V0/V1/V4/V5
INST_NOIND  = f"inst{N_INST}_noind"   # V2 independent suffix
INST_RANDBR = f"inst{N_INST}_randbr"  # V3 independent suffix

# ── Dataset configuration ─────────────────────────────────────────
#   source_number : total number of source-side columns
#   n_instance    : number of source-side tuples (emb_sm.py --n_instance),
#                   must match V0/V1
#   targets       : list of target subdirectories
#
# NOTE: For TPCH, please verify n_instance against the actual V0/V1 values
#       in data/TPCH/experiment_config.txt (originally named shiyan_peizhi.txt)
DATASETS = {
    "MusicRecordings": dict(source_number=6,  n_instance=658,     targets=[f"target{i}" for i in range(1, 7)]),
    "Movielens":       dict(source_number=13, n_instance=1010133, targets=[f"target{i}" for i in range(1, 7)]),
    "TPCH":            dict(source_number=61, n_instance=86806,   targets=[f"target{i}" for i in range(1, 9)]),
}


# ══════════════════════════════════════════════════════════════
# Utility functions
# ══════════════════════════════════════════════════════════════

def load_sampled_target_instances(target_csv, n_inst=N_INST, seed=RANDOM_SEED):
    """
    Read target.csv and sample n_inst rows in exactly the same way as
    DepySM_batch_more.
    Returns (header: list[str], instances: list[list[str]]).
    """
    rows = []
    with open(target_csv, mode="r", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)
        for r in reader:
            rows.append(list(r))
    if n_inst is not None and n_inst < len(rows):
        rng = np.random.default_rng(seed=seed)
        idx = sorted(rng.choice(len(rows), size=n_inst, replace=False).tolist())
        rows = [rows[i] for i in idx]
    return header, rows


def _run_emb(data_name, target_subdir, inst_suffix, emb_dim, n_instance,
             no_ind_edges=False):
    """Unified wrapper for the emb_sm.py subprocess call."""
    cmd = [
        TARGET_PYTHON, "pane/emb_sm.py",
        "--data",        data_name,
        "--target",      target_subdir,
        "--inst_suffix", inst_suffix,
        "--d",           str(emb_dim),
        "--t",           str(ITER_NUM),
        "--kappa",       str(KAPPA),
        "--n_instance",  str(n_instance),
    ]
    if no_ind_edges:
        cmd.append("--no_ind_edges")  # V2: skip IND edges in the AID-Graph
    subprocess.call(cmd)


def _load_node_emb(emb_path, source_number, target_number, emb_dim):
    """Read PANE forward/backward embedding files and concatenate into a node embedding matrix."""
    emb_f = emb_path + ".f"
    emb_b = emb_path + ".b"
    if not (os.path.exists(emb_f) and os.path.exists(emb_b)):
        return None
    Xf = np.fromfile(emb_f, dtype=np.float64).reshape(
        source_number + target_number, emb_dim // 2)
    Xb = np.fromfile(emb_b, dtype=np.float64).reshape(
        source_number + target_number, emb_dim // 2)
    return np.hstack([Xf, Xb])


def _run_refinement(sim_matrix, target_instances, data_name, dep_mode):
    """Unified wrapper for refinement_iterative with hyperparameters fixed to REFINE_PARAMS."""
    return refinement_iterative(
        similarity_matrix=sim_matrix,
        target_instances=target_instances,
        data=data_name,
        max_iter=REFINE_PARAMS["max_iter"],
        patience=REFINE_PARAMS["patience"],
        k_min=REFINE_PARAMS["k_min"],
        k_max=REFINE_PARAMS["k_max"],
        decay_factor=REFINE_PARAMS["decay"],
        score_ceiling=REFINE_PARAMS["ceiling"],
        dep_mode=dep_mode,
        verbose=False,
    )


def _self_check_vs_v1(sim, data_dir, target_subdir, variant_tag):
    """Element-wise equality check against V1 sim_matrix.json (for MusicRecordings self-consistency validation)."""
    v1_path = f"{data_dir}/res/{target_subdir}/{INST_BASE}/sim_matrix.json"
    if not os.path.exists(v1_path):
        return
    v1 = np.array(json.load(open(v1_path, encoding="utf-8")))
    same = np.allclose(np.array(sim), v1)
    print(f"  [{variant_tag} == V1 self-consistency check] {'PASSED' if same else 'MISMATCH (please check)'}")


# ══════════════════════════════════════════════════════════════
# V2: w/o IND-Graph (Emb only)
# ══════════════════════════════════════════════════════════════

def run_v2_noind_graph(data_name, cfg, target_subdir):
    """
    Remove all IND edges when building the AID-Graph, use PANE embedding,
    and do not run ADVR.
    Used to verify the contribution of IND to graph structural information
    propagation during the embedding stage (compared to V1 = full graph + embedding only).
    """
    source_number = cfg["source_number"]
    n_instance    = cfg["n_instance"]
    data_dir      = f"{DATA_DIR_BASE}/{data_name}"
    target_csv    = f"{data_dir}/target/{target_subdir}/target.csv"

    if not os.path.exists(target_csv):
        print(f"[V2-noind][skip] Missing {target_csv}")
        return

    header, target_instances = load_sampled_target_instances(target_csv)
    target_number = len(header)
    emb_dim       = (source_number + target_number - 1) * 2

    tgt_dir  = f"{data_dir}/target/{target_subdir}/{INST_NOIND}"
    res_dir  = f"{data_dir}/res/{target_subdir}/{INST_NOIND}"
    emb_path = f"{data_dir}/emb/{data_name}.{target_subdir}.{INST_NOIND}.{emb_dim}.a.bin"
    os.makedirs(tgt_dir, exist_ok=True)
    os.makedirs(res_dir, exist_ok=True)

    print(f"[V2-noind] {data_name}/{target_subdir}  (emb_dim={emb_dim})")

    # step 1: Bridge Edge (normal top-k) + Mapped Dependency (both fd_edges and
    #         ind_edges are generated, but ind_edges will not be added to the
    #         graph by emb_sm; they are kept for reference only)
    all_candidates = build_bridge(
        data_dir, target_instances, source_number,
        bridge_edge_path=f"{tgt_dir}/bridge_edges.json",
        force_rebuild_profiles=False,
        random_bridge=False,    # V2 uses normal top-k bridge (consistent with V0/V1)
    )
    build_target_edge(
        all_candidates, target_instances, source_number,
        fd_file=f"{data_dir}/source/fds.txt",
        ind_file=f"{data_dir}/source/inds.txt",
        out_fd_path=f"{tgt_dir}/fd_edges.txt",
        out_ind_path=f"{tgt_dir}/ind_edges.txt",
    )

    # step 2: PANE embedding; --no_ind_edges skips source-side + target-side IND edges
    _run_emb(data_name, target_subdir, INST_NOIND, emb_dim, n_instance,
             no_ind_edges=True)

    # step 3: Cosine similarity matrix (no ADVR)
    node_emb = _load_node_emb(emb_path, source_number, target_number, emb_dim)
    if node_emb is None:
        print(f"[V2-noind][skip] Embedding file missing: {emb_path}.f")
        return

    sim = cosine_similarity(node_emb[source_number:], node_emb[:source_number]).tolist()
    out_path = f"{res_dir}/sim_matrix.json"
    json.dump(sim, open(out_path, "w", encoding="utf-8"), indent=2)
    print(f"[V2-noind][ok] → {out_path}")

    # MusicRecordings self-consistency check: when there are no IND edges, V2 should be identical to V1
    _self_check_vs_v1(sim, data_dir, target_subdir, "V2-noind")


# ══════════════════════════════════════════════════════════════
# V3: Random Bridge Edges (originally V2)
# ══════════════════════════════════════════════════════════════

def run_v3_random_bridge(data_name, cfg, target_subdir):
    """
    Replace Bridge Edges with random sampling (build_bridge(random_bridge=True));
    the rest of the AID-Graph (including IND edges) and ADVR remain completely unchanged.
    Output goes to inst_suffix = inst5_randbr.
    """
    source_number = cfg["source_number"]
    n_instance    = cfg["n_instance"]
    data_dir      = f"{DATA_DIR_BASE}/{data_name}"
    target_csv    = f"{data_dir}/target/{target_subdir}/target.csv"

    if not os.path.exists(target_csv):
        print(f"[V3-randbr][skip] Missing {target_csv}")
        return

    header, target_instances = load_sampled_target_instances(target_csv)
    target_number = len(header)
    emb_dim       = (source_number + target_number - 1) * 2

    tgt_dir  = f"{data_dir}/target/{target_subdir}/{INST_RANDBR}"
    res_dir  = f"{data_dir}/res/{target_subdir}/{INST_RANDBR}"
    emb_path = f"{data_dir}/emb/{data_name}.{target_subdir}.{INST_RANDBR}.{emb_dim}.a.bin"
    os.makedirs(tgt_dir, exist_ok=True)
    os.makedirs(res_dir, exist_ok=True)

    print(f"[V3-randbr] {data_name}/{target_subdir}  (emb_dim={emb_dim})")

    # step 1: Random bridge edge; all_candidates (real scores) are returned as
    #         usual for use by build_target_edge
    all_candidates = build_bridge(
        data_dir, target_instances, source_number,
        bridge_edge_path=f"{tgt_dir}/bridge_edges.json",
        force_rebuild_profiles=False,
        random_bridge=True,     # Key switch for V3
    )
    build_target_edge(
        all_candidates, target_instances, source_number,
        fd_file=f"{data_dir}/source/fds.txt",
        ind_file=f"{data_dir}/source/inds.txt",
        out_fd_path=f"{tgt_dir}/fd_edges.txt",
        out_ind_path=f"{tgt_dir}/ind_edges.txt",
    )

    # step 2: PANE embedding (with IND edges; only bridge edges are randomized)
    _run_emb(data_name, target_subdir, INST_RANDBR, emb_dim, n_instance,
             no_ind_edges=False)

    # step 3: Cosine similarity matrix + full ADVR
    node_emb = _load_node_emb(emb_path, source_number, target_number, emb_dim)
    if node_emb is None:
        print(f"[V3-randbr][skip] Embedding file missing: {emb_path}.f")
        return

    sim = cosine_similarity(node_emb[source_number:], node_emb[:source_number]).tolist()
    json.dump(sim, open(f"{res_dir}/sim_matrix.json", "w", encoding="utf-8"), indent=2)

    updated = _run_refinement(sim, target_instances, data_name, dep_mode="all")
    out_path = f"{res_dir}/{UPDATED_FNAME_FULL}"
    json.dump(updated, open(out_path, "w", encoding="utf-8"), indent=2)
    print(f"[V3-randbr][ok] → {out_path}")


# ══════════════════════════════════════════════════════════════
# V4 / V5: FD-only / IND-only validation (originally V3 / V4)
# ══════════════════════════════════════════════════════════════

def run_advr_only(data_name, cfg, target_subdir, dep_mode, out_fname):
    """
    Reuse inst5/sim_matrix.json (shared V0/V1 embeddings); only re-run ADVR.
      dep_mode="fd"  -> V4 FD-only validation
      dep_mode="ind" -> V5 IND-only validation
    The embedding step is not re-run, ensuring embeddings are identical to
    V0/V1 (fairness guarantee).
    """
    data_dir  = f"{DATA_DIR_BASE}/{data_name}"
    res_dir   = f"{data_dir}/res/{target_subdir}/{INST_BASE}"
    sim_path  = f"{res_dir}/sim_matrix.json"

    if not os.path.exists(sim_path):
        print(f"[{dep_mode}-only][skip] Missing {sim_path} (please complete V0/V1 first)")
        return

    sim = json.load(open(sim_path, encoding="utf-8"))
    target_csv = f"{data_dir}/target/{target_subdir}/target.csv"
    if not os.path.exists(target_csv):
        print(f"[{dep_mode}-only][skip] Missing {target_csv}")
        return
    _, target_instances = load_sampled_target_instances(target_csv)

    updated  = _run_refinement(sim, target_instances, data_name, dep_mode=dep_mode)
    out_path = f"{res_dir}/{out_fname}"
    json.dump(updated, open(out_path, "w", encoding="utf-8"), indent=2)

    # Self-consistency check (IND-only on a dataset with no IND should equal V1)
    note = ""
    if dep_mode == "ind":
        same = np.allclose(np.array(updated), np.array(sim))
        note = "  [== V1, IND is empty, self-consistency check PASSED]" if same else "  [!= V1, please check]"
    print(f"[{dep_mode}-only][ok] {data_name}/{target_subdir} -> {out_fname}{note}")


# ══════════════════════════════════════════════════════════════
# Main pipeline
# ══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    for data_name, cfg in DATASETS.items():
        print(f"\n{'#' * 64}\n# {data_name}\n{'#' * 64}")
        for tgt in cfg["targets"]:
            print(f"\n----- {data_name} / {tgt} -----")
            run_v2_noind_graph(data_name, cfg, tgt)                       # V2
            run_v3_random_bridge(data_name, cfg, tgt)                     # V3
            run_advr_only(data_name, cfg, tgt, "fd",  V4_FNAME)           # V4
            run_advr_only(data_name, cfg, tgt, "ind", V5_FNAME)           # V5
    print("\n========== All ablation variants (V2-V5) processing complete ==========")